services:
  - type: web
    name: telegram-stock-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
